---
title: "Activity#2"
author: "Joshua Somosera"
date: "2024-02-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r num1}
install.packages("rvest")
install.packages("httr")
install.packages("polite")

library(rvest)
library(httr)
library(polite)
```

```{r num2}
polite::use_manners(save_as = 'polite_scrape.R')

urllink <- 'https://www.imdb.com/title/tt4589218/reviews?ref_=tt_urv'

session <- bow(url,
               user_agent = "Educational")
session
```

```{r num3}
div_elements <- html_nodes(session_page, 'review-container')

Username <- character(0)
ReviewerDate <- character(0)
ReviewerContent <- character(0)
Rating <- character(0)

for (page in 1:12) 
  Username <- scrape (session) %>%
    html_nodes('span.display-name-link')%>%
    html_text
  Username
  
  ReviewerDate <- scrape (session) %>%
    html_nodes('span.review-date')%>%
    html_text
  ReviewerDate

  ReviewerContent <- scrape (session) %>%
    html_nodes('div.text.show-more__control')%>%
    html_text
  ReviewerContent
  
  
  Rating <- scrape (session) %>%
    html_nodes('span.rating-other-user-rating')%>%
    html_text
  Rating
```

```{r num4}
  DataFrame <- data.frame(Usernames = Username,
                            Reviewer_Date =ReviewerDate,
                            Reviewer_Content = ReviewerContent,
                            Rating = Rating)
  
  
  write.csv(DataFrame, "1DF.csv")
  View(X1DF)  
  
  
```

